services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: indocloth-backend-API
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}  # must point to external DB now
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
      INFERENCE_SERVICE_URL: http://inference-service:8002/inference
      ML_SERVICE_URL: http://inference-service:8000
      MODEL_BASE_PATH: /app/models
      DEBUG: "false"
      SECRET_KEY: ${SECRET_KEY}
      ENVIRONMENT: production
      LOG_LEVEL: INFO
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      STATIC_IMAGES_DIR: /app/fashion_images/dataset_clean
    ports:
      - "8030:8030"
    volumes:
      - ../fashion_images/dataset_clean:/app/fashion_images/dataset_clean:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - indocloth-network
    restart: unless-stopped

  inference-service:
    build:
      context: ./api/fastapi_app
      dockerfile: ../../docker/fastapi.Dockerfile
    container_name: indocloth-inference
    environment:
      MODEL_PATH: /app/models
      OMP_NUM_THREADS: "1"
    ports:
      - "8000:8000"
    volumes:
      - ../MLOps/models:/app/models:ro
    networks:
      - indocloth-network
    restart: unless-stopped

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: indocloth-frontend
    ports:
      - "4020:80"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8030/api/v1
    networks:
      - indocloth-network
    restart: unless-stopped

networks:
  indocloth-network:
    driver: bridge